### ISSUE TITLE
"trash" behaving like rm -rf command | MacOS Catalina 10.15.3

### ISSUE THREAD

**Issue by Manir991** [sindresorhus/trash#93] opened 2020-02-15 23:14 UTC
Hi,
For some reason the "trash" command is behaving like an rm -rf. The file/ directory gets deleted without populating in the trash. Please let me know if there's anything I am missing. 

<img width="928" alt="Screen Shot 2020-02-15 at 5 59 22 PM" src="https://user-images.githubusercontent.com/33009338/74596556-e043c480-501e-11ea-8613-4449f0c8d1ab.png">

**Comment by sindresorhus** [comment] 2020-02-16 15:22
Can you try running the binary used here directly? https://github.com/sindresorhus/macos-trash/releases It's just calling the macOS API for moving to trash, so if the problem is correct, it's a macOS bug.

**Closed** 2020-11-05 12:30 UTC
