### ISSUE TITLE
Support undo/put back?

### ISSUE THREAD

**Issue by erikjalevik** [sindresorhus/trash#74] opened 2018-06-16 07:09 UTC
I am trying to figure out how to programmatically undo a Move To Trash/Recycle Bin from an electron app. It seems much more complicated than I had assumed.

Is it something you would consider supporting in this lib?

**Comment by sindresorhus** [comment] 2018-06-16 08:58
Duplicate of #24

**Closed by sindresorhus** 2018-06-16 08:58 UTC
